routes/web.php
<?php

Auth::routes();

Route::get('/', 'Auth\LoginController@showLoginForm');
Route::resource('categories', 'CategoryController');
Route::get('/tree/{type?}', 'CategoryController@tree')->name('tree');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['title', 'parent_id'];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Classes\CategoryTree;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();

        foreach ($categories as $key => $category) {
            $parent = Category::find($category->parent_id);
            if ($parent) {
                $categories[$key]['parent_title'] = $parent->title;
            }
        }

        return view('categories.index', ['categories' => $categories]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();

        return view('categories.edit', ['categories' => $categories]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validateCategoryFields($request);

        $category = new Category();

        $category->title = $request->title;
        $category->parent_id = isset($request->parent_id) ? $request->parent_id : 0;


        $category->save();

        return redirect()->route('categories.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        $categories = Category::all();

        return view('categories.edit', ['category' => $category, 'categories' => $categories]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Category $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $this->validateCategoryFields($request);

        $category->update($request->all());

        return redirect()->route('categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        Category::destroy($category->id);

        return redirect()->route('categories.index');
    }

    protected function validateCategoryFields($request)
    {
        $this->validate(
            $request,
            [
                'title' => 'required|max:255',
            ]
        );
    }

    public function tree($type = null)
    {
        $tree = new CategoryTree();
        $empty = false;

        switch ($type) {
            case 'recursive':
                $tree->generateRecursive();
                break;
            case 'iterative' :
                $tree->generateIterative();

                break;
            default:
                $empty = true;
                break;
        }

        return view(
            'categories.tree',
            array(
                'type' => $type,
                'list' => $empty ?: $tree->get(),
                'empty' => $empty
            )
        );
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/categories/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-sm-4 mx-auto">
            <h1>{{ isset($category) ? 'Edit' : 'Add' }} category</h1>
            @if (count($errors))
                <div class="alert alert-danger">
                    <ul class="my-0">
                        @foreach ($errors->all() as $error)
                            <li>
                                {{ $error }}
                            </li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form role="form" method="POST"
                  action="{{ isset($category) ? route('categories.update', $category->id) : route('categories.store') }}">
                @if(isset($category))
                    {{ method_field('PATCH') }}
                @endif
                {{ csrf_field() }}
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="form-group col-sm-8">
                                <label for="title">Title</label>
                                <input id="title" class="form-control" name="title" type="text"
                                       value="{{ old('title') ? old('title') : (isset($category->title) ? $category->title : null) }}">
                            </div>
                            <div class="form-group col-sm-4">
                                <label for="category">Parent</label>
                                <select id="category" class="form-control"
                                        name="parent_id"{{ count($categories) < 1 ? 'disabled' : ''}}>
                                    <option value="0">Select</option>
                                    @if(isset($categories) && count($categories) > 0)
                                        @foreach($categories as $parent)
                                            @if((isset($category->id) && $category->id == $parent->id))
                                            @else
                                                <option value="{{ $parent->id }}"
                                                        @if((isset($category) && ($category->parent_id == $parent->id))) selected @endif>
                                                    {{ $parent->title }}
                                                </option>
                                            @endif
                                        @endforeach
                                    @else
                                        <option disabled>No categories</option>
                                    @endif
                                </select>
                            </div>
                        </div>
                        <div class="btn-block">
                            <a href="{{ route('categories.index') }}" class="btn btn-secondary float-left">Cancel</a>
                            <button type="submit" class="btn btn-primary float-right"><i
                                        class="glyphicon glyphicon-floppy-disk"></i> Save
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/categories/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-12">
                <div class="row">
                    <div class="col-sm-8">
                        <h1>Categories</h1>
                    </div>
                    <div class="col-sm-4">
                        <a href="{{ route('categories.create') }}" class="btn btn-primary float-right">Create new</a>
                    </div>
                </div>
                @if(isset($categories) && count($categories)>0)
                    <div class="card border-0">
                        <div class="card-body p-0">
                            <table class="table table-bordered mb-0">
                                <thead>
                                <tr class="d-flex">
                                    <th scope="col" class="col text-center">ID</th>
                                    <th scope="col" class="col-5">Title</th>
                                    <th scope="col" class="col-4">Parent</th>
                                    <th scope="col" class="col">Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($categories as $category)
                                    <tr class="d-flex">
                                        <th scope="row" class="col text-center py-1">
                                            <span class="align-middle">{{ $category->id }}</span>
                                        </th>
                                        <td class="col-5 py-1">
                                            <span class="align-middle">{{ $category->title }}</span>
                                        </td>
                                        <td class="col-4 py-1">
                                            <span class="align-middle">{{ $category->parent_title }}</span>
                                        </td>
                                        <td class="col py-1 text-center">
                                            <a class="btn btn-outline-success btn-sm"
                                               href="{{ route('categories.edit', $category)}}">Edit</a>
                                            <button class="btn btn-outline-danger btn-sm"
                                                    data-toggle="modal"
                                                    data-target="#modalConfirmDelete"
                                                    data-title="{{ $category->title }}"
                                                    data-url="{{ route('categories.destroy', $category)}}">Delete
                                            </button>
                                        </td>
                                    </tr>
                                @endforeach
                            </table>
                        </div>
                    </div>
                @else
                    <div class="card">
                        <div class="card-body">
                            <p class="text-center m-0">No categories yet.</p>
                        </div>
                    </div>
                @endif
            </div>
        </div>
    </div>
@endsection

resources/views/categories/tree.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-12">
                @if(isset($empty) && $empty)
                    <div class="alert alert-warning" role="alert">
                        You passed the wrong generation method to the URL. Try
                        <a href="{{ route('tree', ['type' => 'recursive']) }}">/recursive</a> or
                        <a href="{{ route('tree', ['type' => 'iterative']) }}">/iterative</a>
                        for results.
                    </div>
                @else
                    <h1>{{ !isset($type) ?: ucfirst($type) }} tree</h1>
                    <div class="card">
                        <div class="card-body">
                            @if(empty($list))
                                <div class="text-center">
                                    No categories found
                                </div>
                            @else
                                {!! $list !!}
                            @endif
                        </div>
                    </div>
                @endif
            </div>
        </div>
    </div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script src="{{ asset('js/jquery.js') }}"></script>
    <script src="{!! asset('/js/confirmDelete.js') !!}"></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">
    @auth
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item@if(Route::current()->name() == route('categories.index')) active@endif">
                        <a href="{{ route('categories.index') }}" class="nav-link">Categories</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            Tree <span class="caret"></span>
                        </a>

                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('tree', ['type' => 'recursive']) }}">
                                Recursive
                            </a>
                            <a class="dropdown-item" href="{{ route('tree', ['type' => 'iterative']) }}">
                                Iterative
                            </a>
                        </div>
                    </li>
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>

                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                  style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    @endauth
    <main class="py-4">
        @yield('content')
    </main>
</div>
<div class="modal fade" id="modalConfirmDelete" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Confirm delete</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <form id="confirmDelete" action="" method="POST">
                    {!! method_field('DELETE') !!}
                    {{ csrf_field() }}
                    <button type="submit" class="btn btn-danger">
                        Delete
                    </button>
                </form>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
</body>
</html>